name: 每日宾果题目生成

on:
  schedule:
    - cron: '0 16 * * *'  # UTC时间16:00（北京时间0:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install Pillow jinja2

      - name: 生成题目
        run: python generate_bingo.py

      - name: 提交更新
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "每日更新宾果题目"
          git push
