name: 宾果

on:
  schedule:
    - cron: '0 16 * * *'  # UTC时间16:00（北京时间0:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: pip install jinja2

      - name: 生成题目
        run: python generate_bingo.py

      - name: 渲染Markdown
        run: |
          python -c "
          import json
          from jinja2 import Template
          with open('bingo.json', 'r', encoding='utf-8') as f:
              data = json.load(f)
          with open('README.md', 'r', encoding='utf-8') as f:
              template = Template(f.read())
          with open('README.md', 'w', encoding='utf-8') as f:
              f.write(template.render(grid=data['grid'], winning_path=data['winning_path']))
          "

      - name: 提交更新
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "每日更新宾果题目"
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:main
